media: static
content:
  - name: about
    label: About
    path: src/routes/about/+page.md
    type: file
    fields:
      - name: layout
        label: Layout
        type: string
        default: about
        hidden: true
      - name: body
        label: Body
        type: rich-text
        options:
          image:
            path: static/images
  - name: videos
    label: Videos
    path: src/lib/data/videos.json
    type: file
    icon: film
    fields:
      - name: video
        label: Video Source
        type: object
        list: true
        fields:
          - name: name
            label: Title
            type: string
          - name: desc
            label: Description
            type: rich-text
            options:
              format: html
              image:
                path: static/images
          - name: thumbnail
            label: Thumbnail
            type: image
            options:
              path: static/images
              output: /
          - name: src
            label: Source URL
            type: string
            pattern: ^(https?:\/\/)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
  - name: socials
    label: Socials
    path: src/lib/data/socials.json
    type: file
    icon: circle-user-round
    fields:
      - name: social
        label: Social
        type: object
        list: true
        fields:
          - name: url
            label: URL
            type: string
            pattern: ^(https?:\/\/)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
          - name: name
            label: Name
            type: string